name =input("Enter your name")
surname = input("Enter your surname")
age = int(input("Enter your age"))
marriage = input("Are you married")
income = int(input("What is your monthly income"))
print("name is ", type(name),"surname is a", type(surname),"age is a", type(age),"The answer to marriage is a", type(marriage),"income is a", type(income))
